CREATE TABLE DANE_LOGOWANIA
  (
    login NVARCHAR2 (50) NOT NULL ,
    haslo NVARCHAR2 (50) NOT NULL ,
    typ NVARCHAR2 (9) NOT NULL
  ) ;
ALTER TABLE DANE_LOGOWANIA ADD CHECK ( typ IN ('klient', 'pracownik', 'admin')) ;
ALTER TABLE DANE_LOGOWANIA ADD CONSTRAINT DANE_LOGOWANIA_PK PRIMARY KEY ( login ) ;